site_name: My Docs
site_dir: 'rendered-docs'
theme:
  name: material
  language: ja
  palette:
    primary: brown
    accent: deep orange

plugins:
  - print-site:
      add_to_navigation: true
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: true
      toc_title: '目次'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: false
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:
